Fix/section usage checkbox
istex/istex-dl pull request #117
Opened 2022-08-03 06:40 UTC by NK-WEB-Git

2022-08-03 11:38 UTC, ClementDreptin requested changes
Après avoir cliqué sur le bouton "Télécharger", le formulaire se réinitialise correctement à l'exception de la section Usage qui finit dans un état un peu étrange. J'ai un peu essayé de trouver la raison, sans succès. Je te mets une capture d'écran pour te montrer :
![image](https://user-images.githubusercontent.com/44998961/182598802-57523888-1e85-4b88-9a1f-83bb19192b9c.png)

2022-08-03 11:38 UTC, ClementDreptin commented on src/components/UsageSection/UsageSection.jsx
> +  const handleDisplayingOfUsage = (usageName) => {
Cette fonction pourrait s'écrire plus simplement et sur une ligne comme ça :
```JS
const handleDisplayingOfUsage = usageName => setShouldDisplayUsage(usageName !== 'customUsage');
```

2022-08-18 13:41 UTC, niederlec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design de la Partie "Usage" -  sous partie usage personnalisé - ajout des styles et textes](https://trello.com/c/ebBS69Yj/14-design-de-la-partie-usage-sous-partie-usage-personnalis%C3%A9-ajout-des-styles-et-textes)

2022-09-08 13:33 UTC, ClementDreptin commented
Je rencontre toujours le problème d'état bizarre dans la section Usage décrit dans [mon commentaire précédent](https://github.com/istex/istex-dl/pull/117#pullrequestreview-1060145535).

2022-09-13 08:32 UTC, merged