[FIX] Update icons and style for Navbar bottom
istex/istex-dl pull request #119
Opened 2022-08-10 06:51 UTC by NK-WEB-Git

2022-08-10 08:19 UTC, ClementDreptin requested changes
Quelques petits oublis à corriger donc rien de très compliqué.

Pour les icônes, ils n'ont pas les mêmes aspects que ceux en prod mais ce techniquement les mêmes icônes pour font-awesome. On fait comme on a dit, c'est-à-dire qu'on laisse comme ça pour l'instant et on fera un downgrade de la version de font-awesome si besoin par la suite.

2022-08-10 08:19 UTC, ClementDreptin commented on package-lock.json
> -  "lockfileVersion": 2,
La version de `package-lock.json` n'aurait pas dû être downgrade. Assure-toi d'avoir une version de npm supérieure à 6. Chez moi je suis en 8.5.5, avec Node 14.18.2

2022-08-10 08:19 UTC, ClementDreptin commented on src/components/ShareButton/ShareButton.jsx
> +  console.log({ isFormIncomplete });
Je pense que tu as oublié de l'enlever.

2022-08-18 09:02 UTC, niederlec commented
@NK-WEB-Git ça m'a l'air tout bon.
Je voulais juste que tu me confirmes une chose : j'ai remarqué que même désactivé, le bouton "partager" était cliquable.
Est-ce que c'est un oubli ou bien est-ce que cas est/sera géré dans un autre ticket ou branche ?
![image](https://user-images.githubusercontent.com/1567424/185355792-955efa23-6a5d-4806-bc54-5daf918590cc.png)

2022-08-18 09:19 UTC, niederlec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design menu du bas](https://trello.com/c/k4bNFZYY/50-design-menu-du-bas)

2022-08-19 08:31 UTC, merged