Fix/header errors
istex/istex-dl pull request #120
Opened 2022-08-10 07:00 UTC by NK-WEB-Git

2022-08-10 08:49 UTC, ClementDreptin requested changes
La pointe des tooltips est moins large qu'en prod et l'histoire de l'opacité fait que l'intersection entre la pointe et le rectangle et plus foncé qu'il ne faudrait.

En prod les tooltips sont cliquables, il suffit d'imbriqué le `<Tooltip>` dans le `<a>`.

Pourquoi mettre le tooltip Twitter à gauche et pas en bas avec les autres ? Je me souviens vaguement d'une discussion avec Camille sur la placement de certains tooltips à gauche mais je ne me souviens plus de ce que ça concerné précisément.

Contrairement à la prod, le tooltip apparaît avec une animation de fondu. Je ne trouve pas ça dérangeant personnellement mais je sens que, côté métier, le fait que ce ne soit pas exactement comme en prod ne va pas être très apprécié.

Je suis conscient qu'une grosse partie du style est fait par le composant `Tooltip` et je ne sais pas à quel point il est modifiable donc fais au mieux.

2022-08-18 12:58 UTC, niederlec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design de la Partie "En-tête" - ajout des styles et textes](https://trello.com/c/Tb64bERK/16-design-de-la-partie-en-t%C3%AAte-ajout-des-styles-et-textes)

2022-08-18 13:19 UTC, niederlec requested changes

2022-08-18 13:19 UTC, niederlec commented on src/components/Header/Header.jsx
> +                        animation='duration-500'
```suggestion
                        animation={false}
```

2022-08-18 13:19 UTC, niederlec commented on src/components/Header/Header.jsx
> +                        animation='duration-500'
Merci @NK-WEB-Git 
L'apparence des tooltip est très bien à présent, ainsi que le placement.
Il reste une dernière miniscule modif signalée par Clément pour être complètement iso avec le header de www.istex.fr : supprimer l'animation sur les 4 tooltips.

2022-08-19 06:56 UTC, merged