Fix/history modal
istex/istex-dl pull request #128
Opened 2022-08-31 07:49 UTC by NK-WEB-Git

2022-09-02 09:11 UTC, niederlec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design de la partie "Historique"](https://trello.com/c/y7wvhvVn/29-design-de-la-partie-historique)

2022-09-06 09:45 UTC, ClementDreptin requested changes
Les boutons de téléchargement et de partage des entrées de l'historique ne fonctionnent pas. Le bouton de téléchargement ouvre la modal mais ne lance jamais le téléchargement (une erreur apparaît dans la console). Pour le bouton partager, absolument rien ne se passe, pas d'erreur dans la console mais l'URL n'est pas copiée dans le presse-papiers.

2022-09-06 09:45 UTC, ClementDreptin commented on src/components/HistoryButton/ConfirmDeleteHistoryModal.jsx
> +              Etes-vous sûr de vouloir supprimer<br />
Êtes*

2022-09-07 08:25 UTC, ClementDreptin requested changes
Le téléchargement fonctionne mais le partage ne fonctionne toujours pas, la modal de partage s'ouvre bien mais ce n'est pas la bonne URL qui est copiée. Je t'ai donné le fix dans un autre commentaire.

2022-09-07 08:25 UTC, ClementDreptin commented on src/components/ShareButton/ShareButton.jsx
>      navigator.clipboard.writeText(window.location.href)
Tu as oublié de changer cette ligne, il ne faut plus copier `window.location.href` mais bien `urlToClipboard` car celle cette variable qui contient la bonne URL. J'ai testé chez moi et c'est bien ça qu'il faut faire.

2022-09-07 13:15 UTC, merged