Ajout du champs des catalogues dans le menu de recherche avancée
istex/istex-dl pull request #132
Opened 2022-09-05 09:37 UTC by luidgilemonde

Cette feature ajoute le champs des catalogues dans le menu de recherche avancée, a partir du fichier de configuration avancedFormConfig.js

![image](https://user-images.githubusercontent.com/95218534/188418571-0b63ce4a-3404-448b-af87-58fd6e25468f.png)

2022-09-05 13:51 UTC, ClementDreptin requested changes

2022-09-07 09:05 UTC, luidgi94 commented on src/lib/avancedFormConfig.js
> +        dataTitle: 'Tous champs',
> "Tous les champs", non ? Ou alors je n'ai pas compris...

Je pense que c'était une erreur sur le Ticket et la maquette associé , je vais mettre "Tous les champs" à la place

2022-09-07 09:53 UTC, luidgi94 commented on src/lib/avancedFormConfig.js
> +const catalogList = [
> Je sais que la carte Trello dit
> 
> > Stocker la liste (nom technique, titre, description, catégorie) dans un fichier JSON
> 
> mais il y avait déjà un fichier de config (`src/config.js`), je pense que le tableau `catalogList` peut juste être exporté depuis ce fichier.
Je vais mettre le code dans config.js

2022-09-07 09:53 UTC, luidgi94 commented on src/components/QueryInput/QueryInput.jsx
> +                {catalogList.map((catalogue, index) => (
> Même remarque sur le Français, `catalog` plutôt que `catalogue`.

Très bien

2022-09-07 14:48 UTC, merged